#Cecilia Aurora Robelo Hernandez 

name: Hello World with Workflow
on:
  workflow_dispatch: 

job: 
  #Mi job 1
  Tarea1:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "Hello World"
