# Cecilia Aurora Robelo Hernández

name: Hello World with Workflow

on:
  workflow_dispatch:

jobs:
  Tarea1:
    runs-on: ubuntu-latest

    steps:
      - name: Saludo
        run: echo "Hola Mundo"

      - name: Fecha Actual
        run: date

      - name: Mostrar Usuario
        run: whoami
